description: Pipeline for Google Cloud audit logs

processors:
  - set:
      field: event.ingested
      value: '{{_ingest.timestamp}}'
  - user_agent:
      field: user_agent.original
      ignore_missing: true
  - grok:
      field: orchestrator.resource.type_temp
      patterns:
        - '%{DATA}/%{API_VERSION:orchestrator.api_version}/namespaces/%{DATA:orchestrator.namespace}/%{RESOURCE_TYPE:orchestrator.resource.type}(/%{HOSTNAME:orchestrator.resource.name})?'
        - '%{DATA}/%{API_VERSION:orchestrator.api_version}/%{RESOURCE_TYPE:orchestrator.resource.type}'
        - 'apis/%{RESOURCE_TYPE:orchestrator.resource.type}/%{API_VERSION:orchestrator.api_version}'
        - 'api/%{API_VERSION:orchestrator.api_version}'
        - '%{RESOURCE_TYPE:orchestrator.resource.type}'
      pattern_definitions:
        API_VERSION: (v\d+([a-z]+)?(\d+)?)
        RESOURCE_TYPE: ([a-z]+((\.[a-z0-9]+)+)?)
      ignore_missing: true
  - remove:
      field: orchestrator.resource.type_temp
      ignore_missing: true

on_failure:
  - set:
      field: error.message
      value: '{{ _ingest.on_failure_message }}'
